tasks:
  - init: |
      echo "Start init..."   
      echo "pull docker images..." 
      docker-compose pull
      echo "configure application..."       
      make app.config
      docker-compose up
      echo "setup application..."
      make app.setup
      docker-compose stop
      echo "...init completed."
    command: |
      docker-compose up -d

ports:
  - port: 4000
    onOpen: ignore
  - port: 5432
    onOpen: ignore


github:
  prebuilds:
    addCheck: true


