version: '3.6'
services:
  website:
    build: .
    image: website
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgres/montreal_elixir_dev
    ports:
      - 4000:4000
    depends_on:
      - postgres
  postgres:
    image: postgres:10.5
    container_name: montreal_elixir-postgres
    environment:
      - POSTGRES_DB=montreal_elixir_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
